### PR TITLE
Log check failures

### PR DESCRIPTION
**Pull request by chillu**
@sminnee: Related to the recent outage we talked about

### CODE REVIEW

**Comment by sminnee** [comment]
Note that in the SS4 version of this module we'd want to use PSR-3. Perhaps it's worth creating a `1` branch now that is `3.*` compatible?

**Comment by sminnee** [comment]
I don't know if it blocks merge, but if we merge as-is maybe raise an issue?

**Comment by sminnee** [comment]
I'm happy with this once the tests finish. Keen to get Ingo's view on  3 vs 4 compatibility.

**Comment by chillu** [comment]
Yeah, there's lots of modules which need improvements for 4.x core compat, I don't think that should stop these merges though :) I've created an issue for it: https://github.com/silverstripe-labs/silverstripe-environmentcheck/issues/30

**Pull request merged**
